services: # Define all project services
  nginx: # Reverse proxy web server with SSL
    build:
      context: requirements/nginx/. # Custom Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME} # Domain for SSL
        USER: ${MYSQL_USER}         # UID for certificate
    image: nginx
    container_name: nginx
    restart: on-failure # Restart if fails
    env_file:
      - .env # Environment variables
    ports:
      - "443:443" # HTTPS
    depends_on:
      - wordpress # Starts after WordPress
    volumes:
      - wordpress:/var/www/html # Mounts WP files
    networks:
      - inception # Dedicated network

  wordpress: # WordPress CMS with PHP-FPM
    build: requirements/wordpress/. # Custom Dockerfile
    image: wordpress
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_pass        # Database password
      - admin_pass_wp  # WP admin password
      - user_pass_wp   # WP user password
    expose:
      - "9000" # PHP-FPM port
    depends_on:
      - mariadb # Starts after database
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb: # MariaDB database
    build: requirements/mariadb/. # Custom Dockerfile
    image: mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_pass # Root database password
    expose:
      - "3306" # MariaDB default port
    volumes:
      - mariadb:/var/lib/mysql # Persistent data
    networks:
      - inception

secrets: # Maps password files for secure usage
  db_pass:
    file: ../secrets/pass_mariadb.txt
  admin_pass_wp:
    file: ../secrets/admin_pass_wp.txt
  user_pass_wp:
    file: ../secrets/user_pass_wp.txt

networks:
  inception: # Isolated bridge network
    driver: bridge

volumes:
  wordpress: # Persistent volume for WP files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dramos-j/data/wordpress
  mariadb: # Persistent volume for database data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dramos-j/data/mariadb
