services: # Define os serviços do projeto
  nginx: # Servidor web reverso com SSL
    build:
      context: requirements/nginx/. # Dockerfile customizado
      args:
        DOMAIN_NAME: ${DOMAIN_NAME} # Domínio para SSL
        USER: ${MYSQL_USER}         # UID para certificado
    image: nginx
    container_name: nginx
    restart: on-failure # Reinicia se falhar
    env_file:
      - .env # Variáveis de ambiente
    ports:
      - "443:443" # HTTPS
    depends_on:
      - wordpress # Só inicia após WordPress
    volumes:
      - wordpress:/var/www/html # Monta arquivos do WP
    networks:
      - inception # Rede dedicada

  wordpress: # CMS WordPress com PHP-FPM
    build: requirements/wordpress/. # Dockerfile customizado
    image: wordpress
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_pass        # Senha do banco
      - admin_pass_wp  # Senha admin WP
      - user_pass_wp   # Senha user WP
    expose:
      - "9000" # Porta PHP-FPM
    depends_on:
      - mariadb # Só inicia após banco
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb: # Banco de dados MariaDB
    build: requirements/mariadb/. # Dockerfile customizado
    image: mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_pass # Senha root do banco
    expose:
      - "3306" # Porta padrão MariaDB
    volumes:
      - mariadb:/var/lib/mysql # Persistência
    networks:
      - inception

secrets: # Mapeia arquivos de senha para uso seguro
  db_pass:
    file: ../secrets/pass_mariadb.txt
  admin_pass_wp:
    file: ../secrets/admin_pass_wp.txt
  user_pass_wp:
    file: ../secrets/user_pass_wp.txt

networks:
  inception: # Rede bridge isolada
    driver: bridge

volumes:
  wordpress: # Volume persistente para arquivos do WP
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dramos-j/data/wordpress
  mariadb: # Volume persistente para dados do banco
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dramos-j/data/mariadb
