# Automatically determines the best number of workers
worker_processes auto;

# Sets the file to store the process ID of the master process
pid /var/run/nginx.pid;


# Defines the events block for connection handling
events {
    # Sets the maximum number of simultaneous connections per worker
    # 1024 is a common default value
    worker_connections 1024;
}

# Defines the HTTP server configuration
http {
    # Defines the MIME types for file extensions
    include /etc/nginx/mime.types;

    # Sets the default MIME type if none is found
    default_type application/octet-stream;

    # Enables efficient file transfer
    sendfile on;

    # Keeps connections open for 65s
    keepalive_timeout 65;

    # Includes additional server configurations
    include /etc/nginx/conf.d/*.conf;
}
